show databases;
create database customer;
use Customer;
select * from customer_shopping_behavior;

-- what is the total revenue generated by male vs female customers.
SELECT gender, 
SUM(purchase_amount) AS revenue 
FROM customer_shopping_behavior 
GROUP BY gender;

-- Which customers used a discount but still spent more than the average purchase amount. 
SELECT customer_id, purchase_amount 
FROM customer_shopping_behavior 
WHERE discount_applied = 'Yes' 
AND purchase_amount >= (SELECT AVG(purchase_amount) 
FROM customer_shopping_behavior);

--  Which are the top 5 products with the highest average review rating. 
SELECT item_purchased, 
ROUND(AVG(review_rating), 2) AS 'Average Product Rating' 
FROM customer_shopping_behavior 
GROUP BY item_purchased 
ORDER BY AVG(review_rating) 
DESC LIMIT 5; 

-- Compare the average purchase amounts between standard and express shipping. 
SELECT shipping_type, 
AVG(purchase_amount) 
FROM customer_shopping_behavior 
WHERE shipping_type IN ('Standard' , 'Express') 
GROUP BY shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non subscribers. 
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount), 2) AS avg_spend,
ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_shopping_behavior
GROUP BY subscription_status
ORDER BY total_revenue , avg_spend DESC;

-- Which 5 products have the highest percentage of purchase of purchases with discounts applied. 
SELECT item_purchased,
ROUND(SUM(CASE
WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) * 100,2) AS discount_rate
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_rate 
DESC LIMIT 5;

-- Segment customers into new, returning, and loyal based on their total number of previous purchases, and slow the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case
when previous_purchases = 1 then "New"
when previous_purchases between 2 and 10 then "Returning" else "Loyal" end as customer_segment
from customer_shopping_behavior)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- What are the top 3 most purchased within each category. 
with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank 
from customer_shopping_behavior 
group by category, item_purchased)
select item_rank, category, category, item_purchased, total_orders from item_counts where item_rank <=3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer_shopping_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- What is the revenue contribution of each age group. 
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;

